**Name: Harsh Tank**
---
**Id : 201701460**

**ML LAB-1**

In [124]:
import numpy as np
import numpy.linalg as la

**Question 1:**

In [125]:
W = np.array([[8,5,1,5,6],[5,3,8,7,5],[1,8,10,7,8],[5,7,7,8,9],[6,5,8,9,7]])
print(W)

[[ 8  5  1  5  6]
 [ 5  3  8  7  5]
 [ 1  8 10  7  8]
 [ 5  7  7  8  9]
 [ 6  5  8  9  7]]


In [126]:
################ 1) What is the maximum eigenvalue of W ?

eigvals, eigvecs = la.eig(W)
#print(eigvals)
print(max(eigvals))

32.275416286869884


In [127]:
############### 2) square root of maximum eigenvalue of W^2 

W_2 = np.matmul(W,W)
eigvals, eigvecs = la.eig(W_2)
max_eig = max(eigvals)
root_eig = np.sqrt(max_eig)
print(root_eig)

32.275416286869856


In [128]:
############### 3) the maximum singular value of W

wwt = W @ W.transpose()           # WW^T  same as W^2 since matrix W is symmetric
#print(wwt)
eigvals, eigvecs = la.eig(wwt)
sigvals = np.sqrt(eigvals)
print('Max Singular Value : ',max(sigvals))


##### using svd method in numpy
u, s, vh = np.linalg.svd(W, full_matrices=False)
print(max(s))

Max Singular Value :  32.275416286869856
32.27541628686985


In [129]:
############## 4) Frobenius norm of the matrix

W_T = W.transpose()
a = np.matmul(W,W_T)
frob_norm = np.sqrt(np.trace(a))
print("Frobenius Norm = ",frob_norm)             ## Frobenius norm is sqrt(trace(A*A_transpose))

###################
FROB_norm = la.norm(W,'fro')
print(FROB_norm)

Frobenius Norm =  33.52610922848042
33.52610922848042


In [130]:
############# 5) What is determinant of the matrix? What can you say about its rank?

W_det = la.det(W)
print("Determinant is ",W_det)
print("Since determinant is non-zero, W will have FULL RANK i.e. Rank=min(m,n)=min(5,5)= 5")

print("Rank of W : ",np.linalg.matrix_rank(W))

Determinant is  564.9999999999987
Since determinant is non-zero, W will have FULL RANK i.e. Rank=min(m,n)=min(5,5)= 5
Rank of W :  5


In [131]:
############## 6) eigendecomposition of the symmetric matrix and print the eigenvector matrix Q, and the
##############    diagonal matrix Λ with eigenvalues. Verify that matrix W equals QΛQT

eigvals, eigvecs = la.eig(W)
print("Q = \n",eigvecs)
Λ = np.diag(eigvals)
print("\nΛ (Diag of Eigenvals) = \n",Λ) 
Q=eigvecs
print("\nQ*Λ*Q_Traspose = ")
print(Q@w_eig@Q.transpose())  
print("Hence, Q*Λ*Q_Traspose = W")

Q = 
 [[-0.32686672 -0.78644991 -0.30823314 -0.41153047  0.10143812]
 [-0.39467476  0.04740538  0.68031453 -0.40169827 -0.46668534]
 [-0.49139203  0.60944275 -0.42781773 -0.40420933  0.20174294]
 [-0.50485227 -0.05022796 -0.3091631   0.59515818 -0.54111575]
 [-0.49096643 -0.07284208  0.40441889  0.38946466  0.66212433]]

Λ (Diag of Eigenvals) = 
 [[32.27541629  0.          0.          0.          0.        ]
 [ 0.          7.79874449  0.          0.          0.        ]
 [ 0.          0.         -4.50499151  0.          0.        ]
 [ 0.          0.          0.          0.95343025  0.        ]
 [ 0.          0.          0.          0.         -0.52259951]]

Q*Λ*Q_Traspose = 
[[ 8.  5.  1.  5.  6.]
 [ 5.  3.  8.  7.  5.]
 [ 1.  8. 10.  7.  8.]
 [ 5.  7.  7.  8.  9.]
 [ 6.  5.  8.  9.  7.]]
Hence, Q*Λ*Q_Traspose = W


**Question 2:**

In [132]:
############ 1) What is the value of ||y1||_2 ?

y0 = np.array([[0, 1, 0, 0 ,0]])
y0=y0.transpose()
print("y0 = \n",y0)
b = np.array([[1, 0, 0, 0 ,0]])
b=b.transpose()
print("b = \n",b)
y1 = W@y0 + b
print("y1 = \n",y1)

y1_norm = la.norm(y1,2)
print("1) L2 norm of y1 = ",round(y1_norm,4))

############ 2) What is the value of ||y1||_2/||y0||_2 ?

y0_norm = la.norm(y0,ord=2)
print("L2 norm of y0 = ",round(y0_norm,4))

ans = y1_norm/y0_norm
print("2) ANS = ",round(ans,4))

y0 = 
 [[0]
 [1]
 [0]
 [0]
 [0]]
b = 
 [[1]
 [0]
 [0]
 [0]
 [0]]
y1 = 
 [[6]
 [3]
 [8]
 [7]
 [5]]
1) L2 norm of y1 =  13.5277
L2 norm of y0 =  1.0
2) ANS =  13.5277


**Question 3:**

Consider the quadratic form f(x, y, z) = 3x^2 − 2y^2 + z^2 + 8xy − 5yz + xz.

1. Find the symmetric matrix A corresponding to f
2. How will you check the positive definiteness of the matrix? Is it positive definite, positive semidefinite,
indefinite, negative definite, negative semidefinite?

In [137]:
A = np.array([[3,4,1/2],[4,-2,-5/2],[1/2,-5/2,1]])
print("Symmetric Matrix (A) = \n",A)
eigvals,eigvecs = la.eig(A)
print("Eigen Values = ",eigvals)

print("One eigen value is -ve and 2 are +ve so INDEFINITE ")

## if all eigen values are +ve -> +ve definite
## if eigen values are +ve or zero -> +ve semidefinite
## if all are negative -> -ve definite
## if all are negative or zero -> -ve definite

eigvals,eigvecs = la.eig(A)
min_eig=min(eigvals)
max_eig=max(eigvals)

if (max_eig*min_eig < 0):
    print("INDEFINITE")
elif (max_eig>0):
  if (max_eig*min_eig == 0):
    print("Positive Semidefinite")
  elif (max_eig*min_eig > 0):
    print("Positive Definite")
else:  
  if (max_eig == 0):
    print("Negative Semidefinite")
  elif (max_eig < 0):
    print("Negative Definite")

if (max_eig*min_eig < 0):
    print("INDEFINITE")
elif (max_eig*min_eig == 0):
  if (min_eig==0):
    print("Positive Semidefinite")
  elif (max_eig==0):
    print("Negative Semidefinite")
elif (max_eig*min_eig > 0):
  if (max_eig>0):
    print("Positive Definite")
  elif (max_eig<0):
    print("Negative Definite")

val,vec = la.eig(A)
a=min(val)
b=max(val)
if (b>0 and a<0):
  print("Not Defined")
elif b>0 :
  if (a>0):
    print("positive Definite")
  elif a==0:
    print("Positive semi definite")
elif (a<0):
  if (b==0):
    print("Negative semi Definite")
  elif (b<0):
    print("Negative Definite")


Symmetric Matrix (A) = 
 [[ 3.   4.   0.5]
 [ 4.  -2.  -2.5]
 [ 0.5 -2.5  1. ]]
Eigen Values =  [-5.18058822  5.37650268  1.80408554]
One eigen value is -ve and 2 are +ve so INDEFINITE 
INDEFINITE
INDEFINITE
Not Defined


**Question 4:**
1. What is the norm of vectors v and Av?
2. Is the matrix A orthogonal?

In [134]:
A = (1/3)*np.array([[2,-2,1],[1,2,2],[2,1,-2]])
v_T = np.array([[1,0,1]])
v = v_T.transpose()

print("1) Norm of v = ",la.norm(v))
print("Norm of Av = ",la.norm(A@v))

print("2) A is orthogonal since product of A and its transpose gives Identity Matrix.")
print("\nA*A^T = \n",A@A.transpose())

# A is orthogonal and hence Av mutliplication does not changes norm of v


1) Norm of v =  1.4142135623730951
Norm of Av =  1.4142135623730951
2) A is orthogonal since product of A and its transpose gives Identity Matrix.

A*A^T = 
 [[1.00000000e+00 1.54197642e-17 1.23358114e-17]
 [1.54197642e-17 1.00000000e+00 2.46716228e-17]
 [1.23358114e-17 2.46716228e-17 1.00000000e+00]]
